# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b85d7f0f9c4a71753271b85be6e7149a9a2eca4e8a7df1cd97dbb3b2d524bf54a255a418250a9d66d94e39c8ddd0814b0fad53d982b41a6a12f6803d14de09

test:
  secret_key_base: 48dc74cad61bcf793a1b22deb2591cc9c4878ded6f93719ade2c39252a8b823d7d72b7e0761de00048e3fe18a51d1324f04d97ad751bf2895c1e869060c5fe5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
